import React from 'react';

const FAQSection = () => {
  const faqs = [
    {
      question: "What Are AirNodes?",
      answer:
        "AirNodes are wireless access points forming the access layer of the World Mobile network. They provide last-mile connectivity for voice, text, and data services, connecting users to the network. AirNodes communicate with EarthNodes and AetherNodes using the Internode API to manage user authentication, ensure privacy, and facilitate service delivery."
    },
    {
      question: "Why Should I Host and Operate an AirNode?",
      answer:
        "Hosting and operating an AirNode allows you to earn rewards while expanding internet connectivity in underserved areas. This role supports community growth, and generates revenue based on network usage and service quality."
    },
    {
      question: "What Are the Requirements to Host and Operate an AirNode?",
      answer:
        "To host and operate an AirNode, you need a suitable location such as a rooftop or open area to maximize coverage. Reliable access to power and internet is essential. You must also manage basic maintenance and provide occasional servicing to ensure optimal performance."
    },
    {
      question: "How Do I Start Hosting and Operating an AirNode?",
      answer:
        "To begin, register on the World Mobile platform and select an AirNode model that suits your needs. Complete the verification process and finalize your purchase. For cellular models like Portal and Titan, collaborate with World Mobile technicians for deployment. Fixed wireless models such as Link and Apex are pre-deployed or self-installable."
    },
    {
      question: "How Are Rewards Determined for AirNode Host Operators?",
      answer:
        "Rewards are calculated based on the usage of your AirNode, including data, calls, and texts processed. As a Host Operator, you receive the full share of net revenue generated by your AirNode."
    },    
    {
      question: "Can I Monitor and Manage My AirNode Remotely?",
      answer:
        "Yes, AirNode operators can monitor and manage their nodes remotely using a dedicated dashboard. This tool provides real-time insights into performance, alerts for issues, and options to troubleshoot or adjust configurations efficiently."
    },
    {
      question: "What Are the Available AirNode Models for Hosting and Operating?",
      answer:
        "AirNode models cater to various needs, from small rural deployments to large-scale urban coverage. For example, Link and Apex AirNodes are ideal for fixed wireless connectivity, while Portal and Titan models provide cellular coverage with varying ranges and capacities."
    },
    {
      question: "What Support Is Available for Hosts and Operators?",
      answer:
        "World Mobile provides extensive support, including setup assistance, maintenance guidance, and access to training modules. Operators can also connect with a community of peers through The Club forums for advice and insights."
    },
    {
      question: "Are AirNodes Difficult to Maintain?",
      answer:
        "AirNodes are designed for low maintenance. Operators and hosts must ensure stable power and internet connections, along with secure installation. Support resources and troubleshooting guides are readily available to resolve any issues."
    },
    {
      question: "Will Hosting and Operating an AirNode Affect My Internet Speed?",
      answer:
        "Hosting and operating an AirNode has minimal impact on your internet speed, provided you have a reliable and high-speed connection. Proper bandwidth allocation ensures smooth operation for both your usage and the AirNode."
    },
    {
      question: "What Tax Considerations Should I Be Aware Of?",
      answer:
        "World Mobile does not provide tax advice. Hosts and operators should consult a local tax advisor to understand their obligations based on earnings from AirNode hosting and operations."
    }
  ];

  const faqSchema = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: faqs.map((faq) => ({
      "@type": "Question",
      name: faq.question,
      acceptedAnswer: {
        "@type": "Answer",
        text: faq.answer
      }
    }))
  };

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }}
      />
      <div className="max-w-4xl mx-auto mt-16 text-white">
        <h2 className="text-4xl font-extrabold text-center mb-8">Frequently Asked Questions</h2>
        <div className="space-y-4">
          {faqs.map((faq, index) => (
            <div
              key={index}
              className="collapse collapse-arrow bg-[hsl(277.79deg_78.75%_17.79%_/_19%)] rounded-lg shadow-lg"
            >
              <input type="checkbox" />
              <div className="collapse-title text-lg font-bold">{faq.question}</div>
              <div className="collapse-content text-gray-300">
                <p>{faq.answer}</p>
              </div>
            </div>
          ))}
        </div>
      </div>
    </>
  );
};

export default FAQSection;