/* eslint-disable react/no-unescaped-entities */
import React from 'react';
import '@fortawesome/fontawesome-free/css/all.min.css';

export default function HowWMTxWorks() {
  return (
    <section className="py-16 px-6 text-white">
      <div className="max-w-6xl mx-auto">
        <h2 className="text-4xl font-bold mb-8 text-center">
          The Role of <span className="bg-gradient-to-r from-[#F6642D] via-[#D42E58] to-[#5A2FBA] bg-clip-text text-transparent">WMTx</span> in World Mobile
        </h2>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
          {cardData.map((card, index) => (
            <div
              key={index}
              className="card border border-[#5A2FBA] shadow-md p-6 rounded-md"
              style={{
                backgroundColor: 'oklch(0.14 0.05 330.35 / 0.25)',
                color: 'white',
              }}
            >
              <div className="flex items-center mb-4">
                <i className={`fas ${card.icon} fa-2x text-[#F6642D] mr-3`} aria-hidden="true"></i>
                <h3 className="text-xl font-bold">{card.title}</h3>
              </div>
              <p className="text-gray-300">{card.description}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

const cardData = [
  {
    icon: 'fa-wifi',
    title: 'Empowering Connectivity',
    description: 'World Mobile customers pay for calls, texts, and data using local currency, generating revenue that fuels the network.',
  },
  {
    icon: 'fa-server',
    title: 'EarthNode Operations',
    description: 'EarthNode operators and stakers earn WMTx for processing transactions and delivering vital services to the network.',
  },
  {
    icon: 'fa-random',
    title: 'Decentralized Allocation',
    description: 'Revenue generated by the network is used by World Mobile to purchase WMTx from open markets, ensuring rewards are distributed fairly.',
  },
  {
    icon: 'fa-gift',
    title: 'Rewarding Contributors',
    description: 'Operators and stakers receive WMTx rewards for their role in sustaining and growing the World Mobile ecosystem.',
  },
  {
    icon: 'fa-leaf',
    title: 'Sustainable Growth',
    description: 'With a fixed supply, WMTx maintains its value and supports scalable growth as the network expands globally.',
  },
];
